import type { Metadata } from 'next';

import Link from 'next/link';

export default function Services() {
	return (
		<>
			<section id="service-hero">
				<div className="flex h-[30rem] w-full flex-col justify-center bg-[#edc677] text-center">
					<h1 className="text-8xl">Services</h1>
				</div>
			</section>
			<section id="service-services">
				<div className="flex h-[70rem] w-full">
					<div className="flex w-1/2 flex-col justify-evenly px-12">
						<div>
							<h1 className="mb-8 text-4xl">Service One</h1>
							<p className="text-2xl">
								The following text is placeholder known as
								“lorem ipsum,” which is scrambled Latin used by
								designers to mimic real copy. Lorem ipsum dolor
								sit amet Nullam vel ultricies metus, at
								tincidunt arcu. Morbi vestibulum, ligula ut
								efficitur mollis, mi massa accumsan justo,
								accumsan auctor orci lectus ac ipsum. Proin
								porta nisl sem, ac suscipit lorem dignissim et.
								Curabitur euismod nec augue vitae dictum.
							</p>
						</div>
						<div>
							<h1 className="mb-8 text-4xl">Service Two</h1>
							<p className="text-2xl">
								The following text is placeholder known as
								“lorem ipsum,” which is scrambled Latin used by
								designers to mimic real copy. Lorem ipsum dolor
								sit amet Nullam vel ultricies metus, at
								tincidunt arcu. Morbi vestibulum, ligula ut
								efficitur mollis, mi massa accumsan justo,
								accumsan auctor orci lectus ac ipsum. Proin
								porta nisl sem, ac suscipit lorem dignissim et.
								Curabitur euismod nec augue vitae dictum.
							</p>
						</div>
					</div>
					<div className="flex w-1/2 flex-col justify-evenly px-12">
						<div>
							<h1 className="mb-8 text-2xl">Sub-Service One</h1>
							<p className="text-lg">
								The following text is placeholder known as
								“lorem ipsum,” which is scrambled Latin used by
								designers to mimic real copy. Lorem ipsum dolor
								sit amet Nullam vel ultricies metus, at
								tincidunt arcu.
							</p>
						</div>
						<div>
							<h1 className="mb-8 text-2xl">Sub-Service Two</h1>
							<p className="text-lg">
								The following text is placeholder known as
								“lorem ipsum,” which is scrambled Latin used by
								designers to mimic real copy. Lorem ipsum dolor
								sit amet Nullam vel ultricies metus, at
								tincidunt arcu.
							</p>
						</div>
						<div>
							<h1 className="mb-8 text-2xl">Sub-Service Three</h1>
							<p className="text-lg">
								The following text is placeholder known as
								“lorem ipsum,” which is scrambled Latin used by
								designers to mimic real copy. Lorem ipsum dolor
								sit amet Nullam vel ultricies metus, at
								tincidunt arcu.
							</p>
						</div>
					</div>
				</div>
			</section>
			<section id="service-consultation">
				<div className="flex h-[32rem] flex-col items-center justify-center bg-[#282d30] text-center text-white">
					<h1 className="m-auto text-8xl text-[#b5944d]">
						Book a Consultation
					</h1>
					<p className="text-4xl">
						We’ll walk you through every step of the process.
					</p>
					<div className="m-auto flex h-20 w-96 bg-rose-700 hover:bg-rose-800">
						<Link
							href="/consultation"
							className="m-auto h-full w-full content-center text-lg"
						>
							Book a Consultation
						</Link>
					</div>
				</div>
			</section>
		</>
	);
}

export const metadata: Metadata = {
	title: 'Services | World Wide Access',
	description: 'Generated by create next app',
};
